version: 2
formats: []  # Do not build epub and pdf

# This adds mambaforge for the installation
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

python:
  install:
    - method: pip
      path: .
conda:
  environment: docs/conda-environment.yml